// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbzaDrNXhFx3SeAMgrFuJo70H_9oAR7lI',
    appId: '1:694063430729:web:5d992f737e205c96dd1398',
    messagingSenderId: '694063430729',
    projectId: 'redditclone-140df',
    authDomain: 'redditclone-140df.firebaseapp.com',
    storageBucket: 'redditclone-140df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ9-x0dZLbYHloVvqXRZtqXF2WwDro6R8',
    appId: '1:694063430729:android:722342a02b79f462dd1398',
    messagingSenderId: '694063430729',
    projectId: 'redditclone-140df',
    storageBucket: 'redditclone-140df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_1m-16aAmzDqc_e4PNDnHSgK7jFeGjc0',
    appId: '1:694063430729:ios:0ed51a95daf3c270dd1398',
    messagingSenderId: '694063430729',
    projectId: 'redditclone-140df',
    storageBucket: 'redditclone-140df.appspot.com',
    iosClientId: '694063430729-gnk46dpfpkolp5i0g6df718ni174lnq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_1m-16aAmzDqc_e4PNDnHSgK7jFeGjc0',
    appId: '1:694063430729:ios:0ed51a95daf3c270dd1398',
    messagingSenderId: '694063430729',
    projectId: 'redditclone-140df',
    storageBucket: 'redditclone-140df.appspot.com',
    iosClientId: '694063430729-gnk46dpfpkolp5i0g6df718ni174lnq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneApp',
  );
}
